name: Keep Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Release Keep
      uses: python-semantic-release/python-semantic-release@master
      with:
        git_committer_name: Keep Release Bot
        git_committer_email: no-reply@keephq.dev
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update pyproject.toml
      env:
        NEW_VERSION: ${{ github.event.inputs.new_version }}
      run: |
        sed -i "s/^version = .*/version = \"$NEW_VERSION\"/" pyproject.toml
        git add pyproject.toml
        git commit -m "chore: bump version to $NEW_VERSION"
        git push
